settings: &common
  site_title:      '时尚商圈'
  admin_key:       'china'
  admin_account:   'admin'
  admin_password:  'admin'
  site_role:            ["普通用户", "时尚设计师", "商家(专卖店)", "商家用户(百货店)", "品牌用户"]
  site_upgrade_state:   ["无认证", "认证中", "认证成功"]
  
  crop_original:   "640>"
  crop_small:      "190x190#"
  crop_small_covert: "-gravity north -thumbnail 190x190^ -extent 190x190"
  
  item_original:   "640>"
  item_small:      "60x60#"
  item_small_covert: "-gravity north -thumbnail 60x60^ -extent 60x60"
  
  avatar_original: "190x190#"
  avatar_thumb:    "80x80#"
  avatar_small:    "30x30#"
  avatar_thumb_covert: "-gravity north -thumbnail 80x80^ -extent 80x80"
  
  upgrade_role_title: "您的申请已经收到"
  upgrade_role_content: "您已经申请成为"
  
  
development:
  paperclip_url:  "http://localhost:3000/upload_files/:class/:attachment/:id/:style/:filename"
  paperclip_path: ":rails_root/public/upload_files/:class/:attachment/:id/:style/:filename"
  <<: *common
test:
  paperclip_url:  "http://localhost:3000/upload_files/:class/:attachment/:id/:style/:filename"
  paperclip_path: ":rails_root/public/upload_files/:class/:attachment/:id/:style/:filename"
  <<: *common
production:
  paperclip_url:  "http://211.103.203.236/:class/:attachment/:id/:style/:filename"
  paperclip_path: "/var/www/shangquan/web/public/:class/:attachment/:id/:style/:filename"
  <<: *common