settings: &common
  site_title: '时尚商圈'
  admin_key: 'china'
  admin_account: 'admin'
  admin_password: 'changchun'
  
development:
  upload_host: 'http://localhost:3000'
  <<: *common
production:
  upload_host: 'http://admin.youtuos.com'
  <<: *common